blank_issues_enabled: false
contact_links:
  - name: Gitter Community
    url: https://gitter.im/Gitter url here/community
    about: Talk about this repo and talk about everything not in the above templates
